### ISSUE TITLE
ilo4 fails with multiple rpms

### ISSUE THREAD

**Issue by Kallio** [CSCfi/ansible-role-hp-firmware-upgrade#25]
in case multiple ilo4 rpms available 
 - name: Identifying firmware for ILO
   shell: "yum search {{ ilo_version }} |grep -i hp-firmware"
to 
- name: Identifying firmware for ILO
   shell: "yum search {{ ilo_version }} |grep -i hp-firmware|awk '{print $NR}'"

**Comment by FLiPp3r90** [comment]
Hi @Kallio, please look at the changes in the PR https://github.com/CSCfi/ansible-role-hp-firmware-upgrade/pull/29. This should solve the problem.
